### ISSUE TITLE
[PE-D][Tester D] input not trimmed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-F13-3/tp#114]
Semester type input is not trimmed

![image.png](https://raw.githubusercontent.com/tzixi/ped/main/files/8bee9bc3-665e-4010-b012-78786d626537.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: tzixi/ped#1

**Comment by hrithie** [comment]
Fixed in #146.
