### ISSUE TITLE
[PE-D][Tester C] Example of edit command in UG does not adhere to the correct format

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-F13-3/tp#117]
![image.png](https://raw.githubusercontent.com/nicholas132000/ped/main/files/c73c74fe-0bcc-4116-9e5f-7994e9387e07.png)

![image.png](https://raw.githubusercontent.com/nicholas132000/ped/main/files/259dc0f4-706a-4d41-aee5-96e1cc01846f.png)

The time in the edit command in the UG is not in the required HH:MM format

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: nicholas132000/ped#7

**Comment by Zemdalk** [comment]
Same with #123
