### ISSUE TITLE
[PE-D][Tester C] Maybe good to add a help command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-F13-3/tp#129]
It would be good to add a help command, which list all the available commands and their use cases as the commands generally have many fields, which the user might need some time getting used to, therefore having a help command to display the commands and the fields needed for each command would prevent the user from having to always refer to the user guide for the format of entering the commands

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: nicholas132000/ped#9

**Comment by hrithie** [comment]
Implemented help feature.
