### ISSUE TITLE
[TA Code Review] for Hrithie

### ISSUE THREAD

**Issue by CheahHaoYi** [AY2223S2-CS2113-F13-3/tp#143]
@hrithie

I see that your code contribution generally followed the coding standard and convention as taught in the module, good job! 👍 Here are some of my comments on your code contribution.

- [x] For line 182 of `Parser.java`, `addModuleFlag` can be renamed to reflect that it is a boolean value
- [x] The `ParseAddCommand` in `Parser.java` is too long, consider having some helper function to provide appropriate levels of abstractions
- [x] `UserUtility` class invoked `System.out` to print various items, however, shouldn't printing be handled by the `Ui` class? Consider the overall architecture of your classes and see if you would like to refactor the functionality of each classes.
- [x] For line 199 of `EventList.java`, consider renaming the boolean variable `overlap`
- [x] At line 201 of `EventList.java`, the boolean condition is rather complex, consider breaking it down into smaller boolean conditions or having a function to abstract it out.

I see that you've placed various logging functions throughout your contribution, that's good! 👍 Overall quite well done, keep it up! 😄

**Comment by hrithie** [comment]
Fixed 2 tasks in #146.
