### ISSUE TITLE
Implement UI improvements (timetable)

### ISSUE THREAD

**Issue by matthew-liu-zhenjie** [AY2223S2-CS2113-F13-3/tp#60]

**Comment by hrithie** [comment]
Completed v1.0 and successfully merged to master.

`list -w 6
Showing schedule for semester 1 and week 6

TIME      |MONDAY         |TUESDAY        |WEDNESDAY      |THURSDAY       |FRIDAY         |SATURDAY       |SUNDAY         |
----------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+
08:00     |               |               |               |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
08:30     |               |               |               |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
09:00     |               |               |               |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
09:30     |               |               |               |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
10:00     |               |               |               |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
10:30     |               |               |               |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
11:00     |               |               |               |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
11:30     |               |               |               |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
12:00     |               |               |               |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
12:30     |               |               |               |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
13:00     |               |               |               |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
13:30     |               |               |               |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
14:00     |               |               |               |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
14:30     |               |               |AC5001         |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
15:00     |               |               |AC5001         |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
15:30     |               |               |AC5001         |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
16:00     |               |               |AC5001         |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
16:30     |               |               |AC5001         |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
17:00     |               |               |               |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+
17:30     |               |               |               |               |               |               |               |
          +---------------+---------------+---------------+---------------+---------------+---------------+---------------+

____________________________________________________________`
