### ISSUE TITLE
Bug: Timetable interaction with recurring events 

### ISSUE THREAD

**Issue by matthew-liu-zhenjie** [AY2223S2-CS2113-F13-3/tp#80]
Recurring events are not handled well by `list -w xx` function. The event is not displayed on the date itself and only displayed on the interval after and none after that. 

Test cased used was:
`add -e test1 -st 10:00 -sd 2023/03/28 -et 12:00 -ed 2023/03/28 -r 1 W`
`list -w 11 `(the week it occurs) does not list it, but `list -w 12` displays the event. "list -w 13" does not display it though.

This is a pretty feature-breaking bug.

@hrithie @kyrixn

**Comment by matthew-liu-zhenjie** [comment]
Noted, will it be possible to implement it before 2.0? If not we can shift it to 2.1.

**Comment by hrithie** [comment]
Unlikely to be implemented before 2.0 and will need to be shifted to 2.1

**Comment by matthew-liu-zhenjie** [comment]
Solved by #103
