### ISSUE TITLE
Bug: Timetable does not accurately portray timetable

### ISSUE THREAD

**Issue by matthew-liu-zhenjie** [AY2223S2-CS2113-F13-3/tp#81]
What: Lessons seem to be displayed as starting half an hour later than actual starting time.

To recreate this, use the command `add -m CG2023 -n 02 -l lecture`. `list -w 13` will show it starting at 16:30. however when `list` is used, the event will show `[E] CG2023 (2023/04/04 16:00 to 2023/04/04 18:00 not recurring) @ ENG-AUD`. Similar issue was encountered with other modules (EE2026, IE2111, CS2113). I think we should display the modules as they would be shown on NUSMods.

**Comment by matthew-liu-zhenjie** [comment]
@hrithie

**Comment by hrithie** [comment]
Thanks for reporting! Will work on fixing it ASAP.

**Comment by hrithie** [comment]
Fixed in #86. 
Do help to check and let me know if issue persists, thanks!
